In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.2-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.8/81.8 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.2

In [ ]:
from category_encoders import OneHotEncoder
from sklearn.impute import SimpleImputer

In [ ]:
# Data Cleaning
#Data Quality: The data cleaning steps, such as handling missing values and removing duplicates,
# ensure data quality and improve the reliability of the analysis. This indicates a concern for accurate and reliable insights.
def wrangle(filepath):
    # Read CSV file
    data = pd.read_csv(filepath,delimiter=';')
    df = data.sample(frac=0.05, random_state=42)
#Handle missing values
    df = df.dropna()



    duplicate_values = df.duplicated().sum()

    if duplicate_values.sum() > 0:
        # Function to handle missing values
        def handle_duplicate_values(df):
            # Remove duplicate rows
            df.drop_duplicates(inplace=True)
            return df

        df = handle_duplicate_values(df)

    df.reset_index()



    return df
df=wrangle('/content/bank-additional-full.csv')
#print(df.columns)
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2059 entries, 32884 to 25526
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             2059 non-null   int64
 1   job             2059 non-null   object
 2   marital         2059 non-null   object
 3   education       2059 non-null   object
 4   default         2059 non-null   object
 5   housing         2059 non-null   object
 6   loan            2059 non-null   object
 7   contact         2059 non-null   object
 8   month           2059 non-null   object
 9   day_of_week     2059 non-null   object
 10  duration        2059 non-null   int64
 11  campaign        2059 non-null   int64
 12  pdays           2059 non-null   int64
 13  previous        2059 non-null   int64
 14  poutcome        2059 non-null   object
 15  emp.var.rate    2059 non-null   float64
 16  cons.price.idx  2059 non-null   float64
 17  cons.conf.idx   2059 non-null   float64
 18  euribor3m       2059 non-null   float64
 19  nr.employed     2059 non-null   float64
 20  y               2059 non-null   object
dtypes: float64(5), int64(5), object(11)
memory usage: 353.9+ KB
None

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
32884,57,technician,married,high.school,no,no,yes,cellular,may,mon,...,1,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,no
3169,55,unknown,married,unknown,unknown,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,no
32206,33,blue-collar,married,basic.9y,no,no,no,cellular,may,fri,...,1,999,1,failure,-1.8,92.893,-46.2,1.313,5099.1,no
9403,36,admin.,married,high.school,no,no,no,telephone,jun,fri,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.967,5228.1,no
14020,27,housemaid,married,high.school,no,yes,no,cellular,jul,fri,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,no

In [ ]:
# Apply binary encoding for the 'y' column (output variable)
df['y'] = df['y'].map({'no': 0, 'yes': 1})
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
32884,57,technician,married,high.school,no,no,yes,cellular,may,mon,...,1,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,0
3169,55,unknown,married,unknown,unknown,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.860,5191.0,0
32206,33,blue-collar,married,basic.9y,no,no,no,cellular,may,fri,...,1,999,1,failure,-1.8,92.893,-46.2,1.313,5099.1,0
9403,36,admin.,married,high.school,no,no,no,telephone,jun,fri,...,4,999,0,nonexistent,1.4,94.465,-41.8,4.967,5228.1,0
14020,27,housemaid,married,high.school,no,yes,no,cellular,jul,fri,...,2,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18355,28,admin.,single,high.school,no,yes,no,cellular,jul,thu,...,6,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,0
40710,30,technician,single,professional.course,no,no,no,cellular,sep,tue,...,1,999,5,failure,-1.1,94.199,-37.5,0.877,4963.6,0
31407,51,entrepreneur,single,basic.9y,no,yes,no,cellular,may,wed,...,3,999,0,nonexistent,-1.8,92.893,-46.2,1.334,5099.1,1
28317,35,admin.,single,university.degree,no,yes,no,cellular,apr,wed,...,1,999,0,nonexistent,-1.8,93.075,-47.1,1.445,5099.1,0
25526,41,services,divorced,high.school,no,yes,no,cellular,nov,wed,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.120,5195.8,0

In [ ]:
 # OneHotEncoder with use_cat_names=True
one_hot_encoder = OneHotEncoder(use_cat_names=True)

        # SimpleImputer
imputer = SimpleImputer()

        # Apply transformations
df = one_hot_encoder.fit_transform(df)

In [ ]:
!pip install pandas-profiling

Requirement already satisfied: pandas-profiling in /usr/local/lib/python3.10/dist-packages (3.6.6)
Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.10/dist-packages (from pandas-profiling) (4.5.1)
Requirement already satisfied: scipy<1.12,>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.11.3)
Requirement already satisfied: pandas!=1.4.0,<2.1,>1.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib<4,>=3.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (3.7.1)
Requirement already satisfied: pydantic<2,>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.10.13)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (6.0.1)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (3.1.2)
Requirement already satisfied: visions[type_image_path]==0.7.5 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.7.5)
Requirement already satisfied: numpy<1.24,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.23.5)
Requirement already satisfied: htmlmin==0.1.12 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.1.12)
Requirement already satisfied: phik<0.13,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.12.3)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (2.31.0)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (4.66.1)
Requirement already satisfied: seaborn<0.13,>=0.10.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.10)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (0.14.0)
Requirement already satisfied: typeguard<3,>=2.13.2 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (2.13.3)
Requirement already satisfied: imagehash==4.3.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (4.3.1)
Requirement already satisfied: wordcloud>=1.9.1 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.9.2)
Requirement already satisfied: dacite>=1.8 in /usr/local/lib/python3.10/dist-packages (from ydata-profiling->pandas-profiling) (1.8.1)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (1.4.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.10/dist-packages (from imagehash==4.3.1->ydata-profiling->pandas-profiling) (9.4.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (23.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (3.1)
Requirement already satisfied: tangled-up-in-unicode>=0.0.4 in /usr/local/lib/python3.10/dist-packages (from visions[type_image_path]==0.7.5->ydata-profiling->pandas-profiling) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2<3.2,>=2.11.1->ydata-profiling->pandas-profiling) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (0.12.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (4.43.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib<4,>=3.2->ydata-profiling->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.4.0,<2.1,>1.1->ydata-profiling->pandas-profiling) (2023.3.post1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.10/dist-packages (from phik<0.13,>=0.11.1->ydata-profiling->pandas-profiling) (1.3.2)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<2,>=1.8.1->ydata-profiling->pandas-profiling) (4.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.24.0->ydata-profiling->pandas-profiling) (2023.7.22)
Requirement already satisfied: patsy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (0.5.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.2->statsmodels<1,>=0.13.2->ydata-profiling->pandas-profiling) (1.16.0)

In [ ]:
df.columns

Index(['age', 'job_technician', 'job_unknown', 'job_blue-collar', 'job_admin.',
       'job_housemaid', 'job_retired', 'job_services', 'job_entrepreneur',
       'job_unemployed', 'job_management', 'job_self-employed', 'job_student',
       'marital_married', 'marital_divorced', 'marital_single',
       'marital_unknown', 'education_high.school', 'education_unknown',
       'education_basic.9y', 'education_professional.course',
       'education_university.degree', 'education_basic.4y',
       'education_basic.6y', 'default_no', 'default_unknown', 'housing_no',
       'housing_yes', 'housing_unknown', 'loan_yes', 'loan_no', 'loan_unknown',
       'contact_cellular', 'contact_telephone', 'month_may', 'month_jun',
       'month_jul', 'month_aug', 'month_oct', 'month_nov', 'month_apr',
       'month_mar', 'month_sep', 'month_dec', 'day_of_week_mon',
       'day_of_week_thu', 'day_of_week_fri', 'day_of_week_wed',
       'day_of_week_tue', 'duration', 'campaign', 'pdays', 'previous',
       'poutcome_failure', 'poutcome_nonexistent', 'poutcome_success',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y_no', 'y_yes'],
      dtype='object')

In [ ]:
#Feature Engineering:from the corr result i will extract relevant features from the dataset that capture customer behavior have a relation with  the target  y

data=df[['emp.var.rate', 'nr.employed', 'cons.conf.idx','age', 'nr.employed', 'euribor3m', 'campaign', 'pdays','previous','duration','default_no', 'default_unknown', 'contact_cellular', 'contact_telephone', 'poutcome_failure', 'poutcome_nonexistent', 'poutcome_success','y' ]]
data

,emp.var.rate,nr.employed,cons.conf.idx,age,nr.employed,euribor3m,campaign,pdays,previous,duration,default_no,default_unknown,contact_cellular,contact_telephone,poutcome_failure,poutcome_nonexistent,poutcome_success,y
32884,-1.8,5099.1,-46.2,57,5099.1,1.299,1,999,1,371,1,0,1,0,1,0,0,0
3169,1.1,5191.0,-36.4,55,5191.0,4.860,2,999,0,285,0,1,0,1,0,1,0,0
32206,-1.8,5099.1,-46.2,33,5099.1,1.313,1,999,1,52,1,0,1,0,1,0,0,0
9403,1.4,5228.1,-41.8,36,5228.1,4.967,4,999,0,355,1,0,0,1,0,1,0,0
14020,1.4,5228.1,-42.7,27,5228.1,4.963,2,999,0,189,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18355,1.4,5228.1,-42.7,28,5228.1,4.968,6,999,0,87,1,0,1,0,0,1,0,0
40710,-1.1,4963.6,-37.5,30,4963.6,0.877,1,999,5,275,1,0,1,0,1,0,0,0
31407,-1.8,5099.1,-46.2,51,5099.1,1.334,3,999,0,396,1,0,1,0,0,1,0,1
28317,-1.8,5099.1,-47.1,35,5099.1,1.445,1,999,0,58,1,0,1,0,0,1,0,0
25526,-0.1,5195.8,-42.0,41,5195.8,4.120,1,999,0,296,1,0,1,0,0,1,0,0

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
# Separate the features (demographics) and target variable
X = data.drop('y', axis=1)
y = data['y']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential()
model.add(Dense(128, activation='relu', input_dim=X_train.shape[1]))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 128)               2304

 dropout (Dropout)           (None, 128)               0

 dense_1 (Dense)             (None, 64)                8256

 dropout_1 (Dropout)         (None, 64)                0

 dense_2 (Dense)             (None, 32)                2080

 dropout_2 (Dropout)         (None, 32)                0

 dense_3 (Dense)             (None, 1)                 33

=================================================================
Total params: 12673 (49.50 KB)
Trainable params: 12673 (49.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:

# Train the model
history = model.fit(X_train, y_train, epochs=10, batch_size=16, validation_data=(X_test, y_test))

Epoch 1/10
103/103 [==============================] - 2s 5ms/step - loss: 0.4715 - accuracy: 0.8081 - val_loss: 0.2484 - val_accuracy: 0.8932
Epoch 2/10
103/103 [==============================] - 0s 4ms/step - loss: 0.3292 - accuracy: 0.8786 - val_loss: 0.2207 - val_accuracy: 0.8956
Epoch 3/10
103/103 [==============================] - 0s 4ms/step - loss: 0.2782 - accuracy: 0.8907 - val_loss: 0.2086 - val_accuracy: 0.9005
Epoch 4/10
103/103 [==============================] - 0s 3ms/step - loss: 0.2719 - accuracy: 0.8919 - val_loss: 0.2046 - val_accuracy: 0.9102
Epoch 5/10
103/103 [==============================] - 0s 3ms/step - loss: 0.2565 - accuracy: 0.8992 - val_loss: 0.2047 - val_accuracy: 0.9078
Epoch 6/10
103/103 [==============================] - 0s 4ms/step - loss: 0.2404 - accuracy: 0.8901 - val_loss: 0.2027 - val_accuracy: 0.9102
Epoch 7/10
103/103 [==============================] - 0s 4ms/step - loss: 0.2401 - accuracy: 0.8931 - val_loss: 0.1989 - val_accuracy: 0.9126
Epoch 8/10
103/103 [==============================] - 0s 4ms/step - loss: 0.2251 - accuracy: 0.8980 - val_loss: 0.1975 - val_accuracy: 0.9053
Epoch 9/10
103/103 [==============================] - 0s 4ms/step - loss: 0.2237 - accuracy: 0.8992 - val_loss: 0.1997 - val_accuracy: 0.9126
Epoch 10/10
103/103 [==============================] - 0s 4ms/step - loss: 0.2335 - accuracy: 0.8968 - val_loss: 0.1981 - val_accuracy: 0.9150

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

13/13 [==============================] - 0s 2ms/step - loss: 0.1981 - accuracy: 0.9150
Test Loss: 0.1981380730867386
Test Accuracy: 0.9150485396385193